### PR TITLE
Use version 0.4.0 of busylight to get this working on Node 10

### PR DESCRIPTION
**Pull request by ghostlandr**
Haven't actually tested this yet, but I will shortly.

### CODE REVIEW

**Comment by ghostlandr** [comment]
Seems to work locally with only this change. @jamesadarich do you mind publishing this new version to npm?

**Comment by jamesadarich** [comment]
@gdholtslander sure thing, I'll get this sorted for you later today :)

**Comment by jamesadarich** [comment]
@gdholtslander published now, I'm not by a busylight right now to check let me know if all is well for you :)

**Comment by ghostlandr** [comment]
Looks like it's working, thanks!

**Pull request merged**
